spring.application.name=task-manager-rest-api

# Database configuration - using PostgreSQL as the database
# I generally don't hardcode these values in a real application, but for simplicity, I'm including them here.
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=taskuser
spring.datasource.password=taskpass

# JPA and Hibernate configuration

# Automatically create/update database tables based on entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in the console for debugging purposes
spring.jpa.show-sql=true